version: '2.1'

services:
  mysqldb2:
    image: mysql:5
    ports:
      - 3308:3306
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_test
#    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]

